### ISSUE TITLE
add travis

### ISSUE THREAD

**Issue by laktak** [hjson/hjson-rb#1]
@namusyaka  I tried to add a travis build (see [travis.yml](https://github.com/hjson/hjson-rb/blob/travis/.travis.yml)). 

I got as far as having it compile but then it errors on the tests (https://travis-ci.org/hjson/hjson-rb), e.g. `NoMethodError: undefined method`positive?' for -1:Fixnum`

Do you know what the problem is?

**Comment by namusyaka** [comment]
I'll take a look in a few days :)

2016年8月19日金曜日、Christian Zanglnotifications@github.comさんは書きました:

**Comment by namusyaka** [comment]
Fixed and pushed. Thanks for adding an integration of travis.
