### ISSUE TITLE
hjson-rb produces deprecation warning on Ruby 2.4 related to usage of Fixnum

### ISSUE THREAD

**Issue by antekone** [hjson/hjson-rb#4]
Ruby 2.4 deprecated `Fixnum` and `Bignum` in favor of `Integer`. It seems that `hjson-rb` needs to replace references to `Fixnum` with a reference to `Integer`. After simple replacement of the `Fixnum` string the library works without warnings and parses the hjson files correctly (it passes all tests as well), but I'm not sure about backward compatibility.

Example:

    $ ruby Compiler.rb colors.hjson -o colors.dat
    /home/antek/.gem/ruby/2.4.0/gems/hjson-0.1.0/lib/hjson/ast/parser.rb:56: warning: constant ::Fixnum is deprecated

My Ruby version:

    $ ruby --version
    ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

Related links:
1. https://bugs.ruby-lang.org/issues/12005
2. http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

**Comment by laktak** [comment]
@namusyaka could you take a look?

**Comment by namusyaka** [comment]
Fixed. Thanks for your report.
