### ISSUE TITLE
shadowing outer local variable

### ISSUE THREAD

**Issue by mikosullivan** [hjson/hjson-rb#5]
When I try to load hjson I get the following warning:

> /var/lib/gems/2.3.0/gems/hjson-0.1.0/lib/hjson/ast/nodes/string.rb:48: warning: shadowing outer local variable - uffff

Here's the entire ruby script:

<pre>
#!/usr/bin/ruby -w
require 'hjson'
</pre>

Yes, my script turns on warnings. Still, it seems like a warning worth heeding.

Here are some specs:

   Operating system	Ubuntu Linux 16.04.1
   Kernel and CPU	Linux 4.4.0-78-generic on x86_64
   ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

Please let me know if there is other information that would help.

**Comment by laktak** [comment]
thanks, should be fixed.
