### ISSUE TITLE
Relax dependency requirement on JSON

### ISSUE THREAD

**Issue by Tereci** [hjson/hjson-rb#9]
Hi,
I am trying to migrate from JSON to HJSON for config files of my app and I am running into an issue with JSON gem compatibility as HJSON gem requires JSON ~> 2.2.0 while some of the other gems I am using are locked down on older versions of the JSON gem.

Would it be possible to relax the current requirement to a less strict that allows for older versions? I tried to build this gem locally with:
`spec.add_runtime_dependency 'json', '>= 1.7.5'`
and it seems to be working just fine. I can create a pull request if that would help.

**Comment by laktak** [comment]
@namusyaka could you take a look?

**Comment by namusyaka** [comment]
@Tereci Seems good to me. Please send a pull request.

**Comment by Tereci** [comment]
@namusyaka PL created, thank you.
